// CONSTANTS FOR SERVER CONFIGURATION
export const SERVER_PORT = 'SERVER_PORT';
export const JWT_SECRET_KEY = 'JWT_SECRET_KEY';
export const SERVICE_SECRET = 'SERVICE_SECRET';
export const DATABASE_HOST = 'DATABASE_HOST';
export const DATABASE_PORT = 'DATABASE_PORT';
export const DATABASE_USERNAME = 'DATABASE_USERNAME';
export const DATABASE_PASSWORD = 'DATABASE_PASSWORD';
export const DATABASE_NAME = 'DATABASE_NAME';

// Service URLs
export const RESTAURANT_SERVICE_URL = 'RESTAURANT_SERVICE_URL';
export const IDENTITY_SERVICE_URL = 'IDENTITY_SERVICE_URL';
export const PUBLICATIONS_SERVICE_URL = 'PUBLICATIONS_SERVICE_URL';
export const CUSTOMER_SERVICE_URL = 'CUSTOMER_SERVICE_URL';
export const LOCATION_SERVICE_URL = 'LOCATION_SERVICE_URL';
export const DELIVERY_SERVICE_URL = 'DELIVERY_SERVICE_URL';

// ───── Internal Communication Headers ─────
export const HEADER_SERVICE_SECRET = 'x-service-secret';
